import { describe, expect, it } from 'vitest';
import { createDatabaseConnection } from '../db/index.ts';
import { countEveningResponses, getEveningAttendanceFact, getEveningResponse } from '../lib/eveningResponse.ts';
import { isEveningGameEligible } from '../lib/eveningRoster.ts';
import { setParticipantAttendance, setParticipantResponse, serializeEveningParticipant } from '../server/services/eveningParticipantState.ts';
import { assignParticipantToTable } from '../server/services/tableAssignmentService.ts';

const addBase=async(db:any)=>{const now=new Date().toISOString();await db.run(`INSERT INTO players (id,nickname,lifecycle_status,created_at,updated_at) VALUES ('p1','One','normal',?,?)`,[now,now]);await db.run(`INSERT INTO game_evenings (id,title,starts_at,status,default_price,created_at,updated_at) VALUES ('e1','Evening',?,'published',500,?,?)`,[now,now,now]);await db.run(`INSERT INTO evening_tables (id,evening_id,name,format,capacity,created_at,updated_at) VALUES ('t1','e1','Table','STANDARD',10,?,?)`,[now,now]);await db.run(`INSERT INTO evening_participants (id,evening_id,player_id,response_status,registration_status,attendance_status,arrival_status,payment_status,amount_due,amount_paid,created_at,updated_at) VALUES ('ep1','e1','p1','unanswered','unanswered','pending','unknown','unpaid',500,0,?,?)`,[now,now]);};

describe('04B0 canonical evening response and attendance',()=>{
  it('keeps response independent from actual late arrival',async()=>{const db=createDatabaseConnection(':memory:');await addBase(db);await setParticipantResponse(db,'ep1','going');await setParticipantAttendance(db,'ep1','attended_late');const row=serializeEveningParticipant(await db.get<any>('SELECT * FROM evening_participants WHERE id=\'ep1\''));expect(getEveningResponse(row)).toBe('going');expect(getEveningAttendanceFact(row)).toBe('attended_late');expect(row.registration_status).toBe('going');});
  it('counts only five canonical planned responses',()=>{expect(countEveningResponses([{response_status:'going'},{response_status:'late'},{response_status:'thinking'},{response_status:'declined'},{response_status:'unanswered'}])).toEqual({going:1,late:1,thinking:1,declined:1,unanswered:1,responded:4,audience:5});});
  it('allows game seating only after factual arrival',()=>{expect(isEveningGameEligible({response_status:'going',registration_status:'going',attendance_status:'pending',arrival_status:'unknown'} as any)).toBe(false);expect(isEveningGameEligible({response_status:'thinking',registration_status:'thinking',attendance_status:'attended',arrival_status:'on_time'} as any)).toBe(true);});
  it('moving tables never changes response or attendance',async()=>{const db=createDatabaseConnection(':memory:');await addBase(db);await setParticipantResponse(db,'ep1','late');await setParticipantAttendance(db,'ep1','attended_late');await assignParticipantToTable(db,'ep1','t1','declined');const row=await db.get<any>('SELECT * FROM evening_participants WHERE id=\'ep1\'');expect(row.table_id).toBe('t1');expect(row.response_status).toBe('late');expect(row.attendance_status).toBe('attended');expect(row.arrival_status).toBe('late');});
  it('migration is safe to re-run for canonical mirror rows',async()=>{const db=createDatabaseConnection(':memory:');await addBase(db);await setParticipantResponse(db,'ep1','thinking');const before=await db.get<any>('SELECT response_status,registration_status FROM evening_participants WHERE id=\'ep1\'');db.sqlite.exec(requireMigration());const after=await db.get<any>('SELECT response_status,registration_status FROM evening_participants WHERE id=\'ep1\'');expect(after).toEqual(before);});
});

const requireMigration=()=>`UPDATE evening_participants SET response_status=CASE WHEN registration_status='going' THEN 'going' WHEN registration_status='late' THEN 'late' WHEN registration_status='thinking' THEN 'thinking' WHEN registration_status IN ('declined','cancelled') THEN 'declined' WHEN registration_status IN ('registered','confirmed') THEN 'going' WHEN registration_status IN ('invited','waitlist') THEN 'unanswered' ELSE CASE WHEN response_status IN ('going','late','thinking','declined','unanswered') THEN response_status ELSE 'unanswered' END END; UPDATE evening_participants SET registration_status=response_status,arrival_status=CASE WHEN attendance_status='pending' THEN 'unknown' ELSE arrival_status END WHERE registration_status IS NOT response_status OR (attendance_status='pending' AND arrival_status!='unknown');`;
