import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { createDatabaseConnection, type DatabaseWrapper } from '../src/db/index.ts';
import { createApp } from '../src/app.ts';
import { generateOrganizerToken, generatePlayerSessionToken } from '../src/server/auth.ts';
import {
  cancelTournamentRegistration,
  loadTournamentEvening,
  notifyTournamentAudience,
  organizerAddTournamentPlayer,
  prepareTournamentEveningSeating,
  registerTournamentPlayer,
  reorderTournamentReserve,
  reportTournamentPayment,
  reviewTournamentPayment,
} from '../src/server/services/tournamentEveningService.ts';

describe('TOURNAMENT-EVENING-001', () => {
  let db: DatabaseWrapper;
  let app: Awaited<ReturnType<typeof createApp>>;
  let organizerToken: string;
  beforeEach(async () => {
    process.env.ORGANIZER_NOTIFICATION_IDS=''; process.env.ORGANIZER_CHAT_ID='';
    db=createDatabaseConnection(':memory:'); app=await createApp(db); organizerToken=generateOrganizerToken();
  });
  afterEach(()=>db.sqlite.close());

  const addPlayer=async(id:string,gameLevel='tournament',judgeLevel='none')=>{const now=new Date().toISOString();await db.run(`INSERT INTO players (id,nickname,contact_status,lifecycle_status,elo,tokens,created_at,updated_at,game_level,judge_level) VALUES (?,?,'normal','normal',1000,0,?,?,?,?)`,[id,id,now,now,gameLevel,judgeLevel]);};
  const createEvening=async()=>{await addPlayer('judge','tournament','judge');const r=await request(app).post('/api/tournaments/evenings').set('Authorization',`Bearer ${organizerToken}`).send({title:'Тестовый турнир',date:'2026-10-02T17:00:00.000Z',venue:'Суп с котом',judge_player_id:'judge',player_capacity:10,entry_fee_rub:500,prize_fund_rub:3000,prize_allocations:[{place:'1',amount_rub:1500},{place:'2',amount_rub:1000},{place:'3',amount_rub:500}]});expect(r.status).toBe(201);expect(r.body.tournament_evening_flow).toBe(1);return String(r.body.id);};
  const publish=async(id:string)=>{const r=await request(app).post(`/api/tournaments/evenings/${id}/publish`).set('Authorization',`Bearer ${organizerToken}`);expect(r.status).toBe(200);};

  it('enforces exact capacity, judge exclusion and real concurrent 10th/11th registration',async()=>{const id=await createEvening();await publish(id);for(let i=1;i<=11;i++)await addPlayer(`p${i}`);const results=await Promise.all(Array.from({length:11},(_,i)=>registerTournamentPlayer(db,id,`p${i+1}`)));expect(results.filter((r:any)=>r.status==='confirmed')).toHaveLength(10);expect(results.filter((r:any)=>r.status==='reserve')).toHaveLength(1);expect((await db.get<any>("SELECT COUNT(*) AS count FROM tournament_registrations WHERE tournament_id=? AND status='confirmed'",[id]))?.count).toBe(10);await expect(registerTournamentPlayer(db,id,'judge')).rejects.toThrow('JUDGE_CANNOT_REGISTER');});

  it('keeps registration and canonical participants identical before seating',async()=>{const id=await createEvening();await publish(id);for(let i=1;i<=10;i++){await addPlayer(`p${i}`);await registerTournamentPlayer(db,id,`p${i}`);}const reg=await db.all<any>("SELECT player_id FROM tournament_registrations WHERE tournament_id=? AND status='confirmed' ORDER BY slot_number",[id]);const can=await db.all<any>('SELECT player_id FROM tournament_participants WHERE tournament_id=? ORDER BY participant_number',[id]);expect(can.map(r=>r.player_id)).toEqual(reg.map(r=>r.player_id));});

  it('prepares 10 games/100 seats and locks roster after canonical seating exists',async()=>{const id=await createEvening();await publish(id);for(let i=1;i<=10;i++){await addPlayer(`p${i}`);await registerTournamentPlayer(db,id,`p${i}`);}const first=await prepareTournamentEveningSeating(db,id,'organizer-test');expect(first).toMatchObject({ready:true,participants_count:10,games_count:10,seats_count:100,already_prepared:false});const retry=await prepareTournamentEveningSeating(db,id,'organizer-test');expect(retry).toMatchObject({ready:true,already_prepared:true});await expect(cancelTournamentRegistration(db,id,'p1')).rejects.toThrow('ROSTER_ALREADY_SEATED');expect((await loadTournamentEvening(db,id))?.canonical_start_readiness.ready).toBe(true);});

  it('promotes first reserve exactly once under concurrent cancellation with multiple reserves',async()=>{const id=await createEvening();await publish(id);for(let i=1;i<=13;i++){await addPlayer(`p${i}`);await registerTournamentPlayer(db,id,`p${i}`);}await Promise.all([cancelTournamentRegistration(db,id,'p3'),cancelTournamentRegistration(db,id,'p3')]);const p11=await db.get<any>('SELECT status,slot_number FROM tournament_registrations WHERE tournament_id=? AND player_id=?',[id,'p11']);const reserve=await db.all<any>("SELECT player_id,queue_order FROM tournament_registrations WHERE tournament_id=? AND status='reserve' ORDER BY queue_order",[id]);expect(p11).toMatchObject({status:'confirmed',slot_number:3});expect(reserve.map(r=>r.player_id)).toEqual(['p12','p13']);expect(reserve.map(r=>r.queue_order)).toEqual([1,2]);expect((await db.get<any>("SELECT COUNT(*) AS count FROM tournament_evening_audit WHERE tournament_id=? AND action='promote_from_reserve'",[id]))?.count).toBe(1);});

  it('rejects ineligible self-registration and preserves player session identity',async()=>{const id=await createEvening();await publish(id);await addPlayer('club-only','club');expect((await request(app).post(`/api/tournaments/evenings/${id}/register`).set('Cookie',`player_token=${generatePlayerSessionToken('club-only')}`)).status).toBe(403);await addPlayer('eligible');const accepted=await request(app).post(`/api/tournaments/evenings/${id}/register`).set('Cookie',`player_token=${generatePlayerSessionToken('eligible')}`);expect(accepted.status).toBe(200);expect(accepted.body.player_id).toBe('eligible');});

  it('records reported and confirmed actual amounts, supports partial correction and uses actual confirmed total',async()=>{const id=await createEvening();await publish(id);await addPlayer('payer');await registerTournamentPlayer(db,id,'payer');const reported=await reportTournamentPayment(db,id,'payer',300,'частичный перевод');expect(reported).toMatchObject({state:'pending',reported_amount_rub:300});expect((await loadTournamentEvening(db,id))?.payment_totals).toMatchObject({reported_rub:300,confirmed_rub:0,unpaid_count:1});const partial=await reviewTournamentPayment(db,id,'payer','confirmed','organizer-test',300,'подтверждено 300');expect(partial.confirmed_amount_rub).toBe(300);expect((await loadTournamentEvening(db,id))?.payment_totals).toMatchObject({confirmed_rub:300,unpaid_count:1});const corrected=await reviewTournamentPayment(db,id,'payer','confirmed','organizer-test',500,'доплата найдена');expect(corrected.confirmed_amount_rub).toBe(500);expect((await loadTournamentEvening(db,id))?.payment_totals).toMatchObject({confirmed_rub:500,unpaid_count:0});});

  it('supports reject→report→confirm, waived/refunded and payment idempotency with audit amounts',async()=>{const id=await createEvening();await publish(id);await addPlayer('payer');await registerTournamentPlayer(db,id,'payer');const first=await reportTournamentPayment(db,id,'payer',500,'ref1');const retry=await reportTournamentPayment(db,id,'payer',500,'ref1');expect(retry.id).toBe(first.id);await reviewTournamentPayment(db,id,'payer','rejected','organizer-test',undefined,'не найден');await reportTournamentPayment(db,id,'payer',500,'ref2');const confirmed=await reviewTournamentPayment(db,id,'payer','confirmed','organizer-test',450,'частично');const confirmRetry=await reviewTournamentPayment(db,id,'payer','confirmed','organizer-test',450,'частично');expect(confirmRetry.id).toBe(confirmed.id);await reviewTournamentPayment(db,id,'payer','waived','organizer-test',undefined,'гостевой допуск');expect((await loadTournamentEvening(db,id))?.payment_totals.confirmed_rub).toBe(0);await reviewTournamentPayment(db,id,'payer','refunded','organizer-test',450,'возврат');expect((await loadTournamentEvening(db,id))?.payment_totals.confirmed_rub).toBe(0);const audit=await db.all<any>("SELECT action,actor_id,payload_json FROM tournament_evening_audit WHERE tournament_id=? AND player_id=? AND action LIKE 'payment_%'",[id,'payer']);expect(audit.every(r=>r.actor_id)).toBe(true);expect(audit.some(r=>String(r.payload_json||'').includes('450'))).toBe(true);});

  it('does not let a repeated player report downgrade organizer-confirmed payment and cannot self-confirm',async()=>{const id=await createEvening();await publish(id);await addPlayer('payer');await registerTournamentPlayer(db,id,'payer');await reportTournamentPayment(db,id,'payer',500);await reviewTournamentPayment(db,id,'payer','confirmed','organizer-test',500);await expect(reportTournamentPayment(db,id,'payer',500)).rejects.toThrow('PAYMENT_REVIEW_REQUIRED');const playerCookie=`player_token=${generatePlayerSessionToken('payer')}`;const response=await request(app).post(`/api/tournaments/evenings/${id}/players/payer/payment`).set('Cookie',playerCookie).send({state:'confirmed',amount_rub:500});expect(response.status).toBe(401);});

  it('keeps tournament payments isolated from tokens and regular payment domains',async()=>{const id=await createEvening();await publish(id);await addPlayer('payer');await registerTournamentPlayer(db,id,'payer');const before=(await db.get<any>('SELECT tokens FROM players WHERE id=?',['payer']))?.tokens;await reportTournamentPayment(db,id,'payer',250);await reviewTournamentPayment(db,id,'payer','confirmed','organizer-test',250);expect((await db.get<any>('SELECT tokens FROM players WHERE id=?',['payer']))?.tokens).toBe(before);});

  it('retries partial publication notification failure without duplicates',async()=>{const id=await createEvening();await addPlayer('p1');await addPlayer('p2');await db.run('UPDATE players SET telegram_user_id=? WHERE id=?',['101','p1']);await db.run('UPDATE players SET telegram_user_id=? WHERE id=?',['102','p2']);await db.run('UPDATE tournaments SET published_at=? WHERE id=?',[new Date().toISOString(),id]);const originalRun=db.run.bind(db);let failed=false;db.run=async(sql:string,params:any[]=[])=>{if(!failed&&sql.includes('INSERT INTO personal_notification_deliveries')&&String(params[1])==='p2'){failed=true;throw new Error('simulated delivery ledger failure');}return originalRun(sql,params);};const first=await notifyTournamentAudience(db,id);expect(first.complete).toBe(false);expect(first.failed_player_ids).toContain('p2');db.run=originalRun;const second=await notifyTournamentAudience(db,id);expect(second.complete).toBe(true);expect((await db.get<any>("SELECT COUNT(*) AS count FROM personal_notification_deliveries WHERE event_type='tournament_published' AND player_id IN ('p1','p2')"))?.count).toBe(2);expect((await db.get<any>("SELECT COUNT(*) AS count FROM personal_notification_deliveries WHERE event_type='tournament_published' AND player_id='p1'"))?.count).toBe(1);});

  it('attributes organizer add/reorder/remove/payment mutations and system promotion explicitly',async()=>{const id=await createEvening();await db.run('UPDATE tournaments SET published_at=? WHERE id=?',[new Date().toISOString(),id]);for(let i=1;i<=12;i++)await addPlayer(`p${i}`);for(let i=1;i<=12;i++)await organizerAddTournamentPlayer(db,id,`p${i}`,'manual','organizer-test');const reserve=await db.all<any>("SELECT id FROM tournament_registrations WHERE tournament_id=? AND status='reserve' ORDER BY queue_order",[id]);await reorderTournamentReserve(db,id,[reserve[1].id,reserve[0].id],'priority','organizer-test');await cancelTournamentRegistration(db,id,'p1','organizer','organizer-test','removed');await reportTournamentPayment(db,id,'p2',500);await reviewTournamentPayment(db,id,'p2','confirmed','organizer-test',500,'checked');const rows=await db.all<any>('SELECT action,actor_type,actor_id FROM tournament_evening_audit WHERE tournament_id=?',[id]);const organizerMutationActions=new Set(['organizer_add','reserve_reorder','cancel','payment_confirmed']);const organizerMutations=rows.filter(r=>organizerMutationActions.has(String(r.action)));expect(organizerMutations.length).toBeGreaterThan(0);expect(organizerMutations.every(r=>r.actor_type==='organizer'&&r.actor_id==='organizer-test')).toBe(true);expect(rows.some(r=>r.action==='promote_from_reserve'&&r.actor_type==='system'&&r.actor_id==='system')).toBe(true);});

  it('returns an explicit public registration whitelist and canonical UI link only',async()=>{const id=await createEvening();await publish(id);const token=(await db.get<any>('SELECT registration_token FROM tournaments WHERE id=?',[id]))?.registration_token;const response=await request(app).get(`/api/tournaments/registration/${token}`);expect(response.status).toBe(200);expect(Object.keys(response.body).sort()).toEqual(['confirmed_count','date','entry_fee_rub','format','id','judge','lifecycle','notes','player_capacity','player_path','prize_allocations','prize_fund_rub','remaining_places','status','title','venue'].sort());expect(response.body.player_path).toBe(`/player/events/${id}`);for(const forbidden of ['registration_token','judge_player_id','registrations','confirmed','reserves','payment_totals','reviewed_by','organizer_note'])expect(response.body).not.toHaveProperty(forbidden);});

  it('player endpoint exposes only current player payment fields, not organizer truth',async()=>{const id=await createEvening();await publish(id);await addPlayer('payer');await registerTournamentPlayer(db,id,'payer');await reportTournamentPayment(db,id,'payer',300,'own note');await reviewTournamentPayment(db,id,'payer','rejected','organizer-secret',undefined,'private organizer note');const response=await request(app).get(`/api/tournaments/evenings/${id}`).set('Cookie',`player_token=${generatePlayerSessionToken('payer')}`);expect(response.status).toBe(200);expect(response.body.me).not.toHaveProperty('organizer_note');expect(response.body.me).not.toHaveProperty('reviewed_by');expect(response.body).not.toHaveProperty('registrations');expect(response.body).not.toHaveProperty('payment_totals');});

  it('does not rewrite legacy draft or historical canonical tournament data',async()=>{const now=new Date().toISOString();await addPlayer('legacy-player');await db.run(`INSERT INTO tournaments (id,title,date,venue,stage,status,chief_judge_name,notes,game_count,created_at,updated_at) VALUES ('legacy-bogdan','Турнир Богдана 1.08','2026-08-01','legacy','final','completed','Богдан','historical',10,?,?)`,[now,now]);await db.run(`INSERT INTO tournament_participants (id,tournament_id,player_id,display_name,participant_number) VALUES ('legacy-participant','legacy-bogdan','legacy-player','Исторический игрок',1)`);const beforeT=await db.get<any>("SELECT * FROM tournaments WHERE id='legacy-bogdan'"),beforeP=await db.get<any>("SELECT * FROM tournament_participants WHERE id='legacy-participant'");const {ensureTournamentEveningSchema}=await import('../src/db/ensureTournamentEveningSchema.ts');await ensureTournamentEveningSchema(db);expect(await db.get<any>("SELECT * FROM tournaments WHERE id='legacy-bogdan'")).toEqual(beforeT);expect(await db.get<any>("SELECT * FROM tournament_participants WHERE id='legacy-participant'")).toEqual(beforeP);await expect(organizerAddTournamentPlayer(db,'legacy-bogdan','legacy-player','unsafe','organizer-test')).rejects.toThrow('NOT_TOURNAMENT_EVENING');});
});