import React,{useEffect,useState} from 'react';
import {Calendar,ExternalLink,MapPin,Sparkles} from 'lucide-react';
import {api} from '../../lib/api.ts';

type Slot={id:string;slot_number:number;starts_at:string;ends_at:string;price:number;registered_count:number;participants:Array<{id:string;nickname:string}>};
type Plan={event:{assembled:boolean;assembled_slots:number;required_slots:number;required_players_per_slot:number;price_per_game:number};slots:Slot[]};
const tm=(v:string)=>new Date(v).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});

export const PublicJoinView:React.FC<{eveningId:string}>=({eveningId})=>{
 const [evening,setEvening]=useState<any>(null),[plan,setPlan]=useState<Plan|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let off=false;Promise.all([api.getPublicEvening(eveningId),fetch(`/api/public/evenings/${encodeURIComponent(eveningId)}/slots`,{credentials:'same-origin'}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b?.error||'Не удалось загрузить игры');return b})]).then(([e,p])=>{if(!off){setEvening(e);setPlan(p)}}).catch((e:any)=>{if(!off)setError(e?.message||'Вечер не найден')}).finally(()=>{if(!off)setLoading(false)});return()=>{off=true}},[eveningId]);
 if(loading)return <main className="flex min-h-screen items-center justify-center bg-[#090a0d] text-sm text-white/45">Загружаем событие…</main>;
 if(!evening||!plan)return <main className="flex min-h-screen items-center justify-center bg-[#090a0d] p-5 text-white"><div className="rounded-3xl border border-white/10 bg-white/[.045] p-6 text-center">{error||'Событие не найдено'}</div></main>;
 const date=new Date(evening.starts_at),price=Number(plan.event.price_per_game||100);
 return <main className="min-h-screen bg-[#090a0d] px-4 py-7 text-white"><div className="mx-auto max-w-md space-y-4">
  <header className="text-center"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.06] px-3 py-1 text-[11px] uppercase tracking-wider text-white/55"><Sparkles className="h-3.5 w-3.5"/>2LA Noire · Тула</div><h1 className="mt-4 text-2xl font-semibold">{evening.title}</h1></header>
  <section className="rounded-3xl border border-white/10 bg-white/[.045] p-4"><div className="flex items-center gap-3 rounded-2xl bg-black/20 p-3"><Calendar className="h-5 w-5 text-white/55"/><div><div className="text-[10px] uppercase text-white/30">Дата и время</div><div className="text-sm capitalize">{date.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}, {tm(evening.starts_at)}</div></div></div><div className="mt-2 flex items-center gap-3 rounded-2xl bg-black/20 p-3"><MapPin className="h-5 w-5 text-white/55"/><div><div className="text-[10px] uppercase text-white/30">Место</div><div className="text-sm">{evening.venue||'Суп с Котом'}</div></div></div><div className="mt-2 flex justify-between rounded-2xl bg-black/20 p-3 text-sm"><span className="text-white/40">Стоимость</span><b>{price} ₽ / игра</b></div></section>
  <section className="rounded-3xl border border-white/10 bg-white/[.045] p-4"><div className="flex justify-between text-sm"><b>{plan.event.assembled?'Стол собран':'Стол собирается'}</b><span className={plan.event.assembled?'text-emerald-300':'text-white/40'}>{plan.event.assembled_slots}/{plan.event.required_slots} игр</span></div><p className="mt-1 text-xs text-white/35">Стол считается собранным, когда минимум 4 игры набрали по 11 человек.</p></section>
  <section className="space-y-2">{plan.slots.map(s=>{const ready=s.registered_count>=plan.event.required_players_per_slot;return <div key={s.id} className={`rounded-2xl border p-3 ${ready?'border-emerald-300/15 bg-emerald-400/[.06]':'border-white/10 bg-white/[.035]'}`}><div className="flex justify-between"><div><b className="text-sm">Игра {s.slot_number} · {tm(s.starts_at)}–{tm(s.ends_at)}</b><div className={`mt-1 text-xs ${ready?'text-emerald-300':'text-white/40'}`}>{s.registered_count}/{plan.event.required_players_per_slot} игроков{ready?' · собрано':''}</div></div><span className="text-xs text-white/35">{s.price} ₽</span></div>{s.participants.length>0&&<div className="mt-2 flex flex-wrap gap-1">{s.participants.map(p=><span key={p.id} className="rounded-full bg-black/20 px-2 py-1 text-[10px] text-white/60">{p.nickname}</span>)}</div>}</div>})}</section>
  <section className="rounded-3xl border border-white/10 bg-white/[.045] p-5"><h2 className="font-semibold">Выбрать свои игры</h2><p className="mt-1 text-sm leading-6 text-white/45">В кабинете игрока можно отметить конкретные игровые слоты. Сумма считается автоматически: 100 ₽ за каждую выбранную игру.</p><a href="/player/events" className="mt-4 flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white font-semibold text-black">Открыть календарь и выбрать игры <ExternalLink className="h-4 w-4"/></a></section>
 </div></main>;
};
