import { Router } from 'express';
import { getDb } from '../../db/index.ts';
import { requireOrganizerAuth } from '../auth.ts';
import baseRouter from './gamesRoutesBase.ts';
import { JudgeAssignmentError, resolveJudgeAssignment } from '../services/judgeAssignmentService.ts';
import { getEveningAttendanceFact } from '../../lib/eveningResponse.ts';
import { requiredJudgeLevelForEveningFormat } from '../../db/ensureJudgeAuthoritySchema.ts';

const router = Router();
const safeJsonParse = <T = any>(value: unknown, fallback: T): T => { if (typeof value !== 'string' || !value.trim()) return fallback; try { return JSON.parse(value) as T; } catch { return fallback; } };
const normalizeGame = (row: any) => { const clubProtocol=safeJsonParse<any>(row.protocol_text,null);const isClubProtocol=Boolean(clubProtocol&&clubProtocol.version===1&&clubProtocol.kind==='club_evening_protocol');return {...row,slots:safeJsonParse(row.slots_json,[]),table_name:row.table_name??null,club_protocol:isClubProtocol?clubProtocol:null,status:isClubProtocol?(clubProtocol.protocol?.status||'draft'):row.winner_team==='draft'?'draft':'completed'}; };

const validateEveningGameSeats=async(db:any,eveningId:string,seats:any[])=>{
  if(!Array.isArray(seats)||seats.length!==10)throw new Error('Для игры необходимо выбрать ровно 10 игроков');const seatNumbers=seats.map(s=>Number(s.seat_number));const ids=seats.map(s=>String(s.participant_id||''));if(new Set(seatNumbers).size!==10||seatNumbers.some(n=>!Number.isInteger(n)||n<1||n>10))throw new Error('Места должны быть уникальными числами от 1 до 10');if(ids.some(id=>!id)||new Set(ids).size!==10)throw new Error('Один игрок не может занимать несколько мест');const placeholders=ids.map(()=>'?').join(',');const rows=await db.all(`SELECT ep.id AS participant_id,ep.player_id,ep.evening_id,ep.response_status,ep.registration_status,ep.attendance_status,ep.arrival_status,p.nickname,p.full_name FROM evening_participants ep JOIN players p ON p.id=ep.player_id WHERE ep.id IN (${placeholders})`,ids);if(rows.length!==10||rows.some((r:any)=>r.evening_id!==eveningId))throw new Error('Все выбранные игроки должны быть участниками этого вечера');const absent=rows.filter((r:any)=>!['attended_on_time','attended_late'].includes(getEveningAttendanceFact(r)));if(absent.length)throw new Error(`В игру можно посадить только фактически пришедших игроков: ${absent.map((r:any)=>r.nickname||r.full_name||r.participant_id).join(', ')}`);const byId=new Map(rows.map((r:any)=>[r.participant_id,r]));return seats.map(s=>{const source:any=byId.get(String(s.participant_id));return {participant_id:String(s.participant_id),player_id:source.player_id,seat_number:Number(s.seat_number),display_name:source.nickname||source.full_name||`Игрок ${s.seat_number}`,role:s.role??null};}).sort((a,b)=>a.seat_number-b.seat_number);
};
const buildInitialClubProtocol=(seats:any[])=>({version:1,kind:'club_evening_protocol',protocol:{game_id:'',status:'draft',winner_team:null,end_reason:'normal',ppk_culprit_participant_id:null,first_killed_participant_id:null,zero_round_voted_participant_id:null,best_move_participant_id:null,best_move_source:null,best_move_seats:[],best_moves:[],votes:[],shots:[],replacement:null,judge_notes:null,best_move_score:0},player_results:seats.map(s=>({participant_id:s.participant_id,player_id:s.player_id,seat_number:s.seat_number,display_name:s.display_name,role:s.role,exit_type:'alive',exit_order:null,regular_fouls:0,minor_technical_fouls:0,major_technical_fouls:0,technical_fouls:0,judge_bonus:0,protocol_bonus:0,penalty_points:0,disciplinary_penalty_points:0,removal_reason:null,ci_points:0,color_protocol:[],notes:null}))});
const clubSlotsFromResults=(results:any[])=>results.slice().sort((a,b)=>Number(a.seat_number)-Number(b.seat_number)).map(r=>({slot_num:Number(r.seat_number),participant_id:r.participant_id,player_id:r.player_id,nickname:r.display_name,role:r.role,team:r.role==='mafia'||r.role==='don'||r.role==='Мафия'||r.role==='Дон'?'Чёрные':r.role?'Красные':null,exit_reason:r.exit_type||'alive',fouls:r.regular_fouls||0,minor_technical_fouls:r.minor_technical_fouls||0,major_technical_fouls:r.major_technical_fouls||0}));

router.post('/evening/:eveningId',requireOrganizerAuth,async(req,res)=>{try{const eveningId=String(req.params.eveningId);const db=(req as any).db||(await getDb());const evening=await db.get<any>('SELECT * FROM game_evenings WHERE id=?',[eveningId]);if(!evening)return res.status(404).json({error:'Вечер не найден'});const tableId=req.body?.evening_table_id?String(req.body.evening_table_id):null;if(tableId&&!await db.get('SELECT id FROM evening_tables WHERE id=? AND evening_id=?',[tableId,eveningId]))return res.status(400).json({error:'Выбранный стол не относится к этому вечеру'});const judge=await resolveJudgeAssignment(db,{judge_player_id:req.body?.judge_player_id??null,judge_name:req.body?.judge_name??null,required_level:req.body?.judge_player_id?requiredJudgeLevelForEveningFormat(evening.format):undefined});const seats=await validateEveningGameSeats(db,eveningId,req.body?.seats||[]);const now=new Date().toISOString();const next=await db.get<any>('SELECT COALESCE(MAX(global_game_number),0)+1 AS next_number FROM games');const protocol=buildInitialClubProtocol(seats);const insert=await db.run(`INSERT INTO games (evening_id,evening_table_id,global_game_number,game_date,winner_team,winner_label,judge_name,judge_player_id,protocol_text,slots_json,created_at) VALUES (?,?,?,?,'draft','Черновик',?,?,?,?,?)`,[eveningId,tableId,Number(next?.next_number||1),evening.starts_at||now,judge.judge_name,judge.judge_player_id,JSON.stringify(protocol),JSON.stringify(clubSlotsFromResults(protocol.player_results)),now]);const id=Number(insert.lastID);protocol.protocol.game_id=String(id);await db.run('UPDATE games SET protocol_text=? WHERE id=?',[JSON.stringify(protocol),id]);const row=await db.get(`SELECT g.*,et.name AS table_name FROM games g LEFT JOIN evening_tables et ON et.id=g.evening_table_id WHERE g.id=?`,[id]);return res.status(201).json(normalizeGame(row));}catch(err:any){return res.status(err instanceof JudgeAssignmentError?400:400).json({error:err.message||'Не удалось создать игру'});}});
router.use(baseRouter);
export default router;
