from pathlib import Path
p = Path('src/tests/clubGameTokenSettlement.test.ts')
text = p.read_text(encoding='utf-8')
text = text.replace("import { beforeEach, describe, expect, it } from 'vitest';", "import { afterEach, beforeEach, describe, expect, it } from 'vitest';\nimport Database from 'better-sqlite3';\nimport fs from 'node:fs';\nimport os from 'node:os';\nimport path from 'node:path';\nimport crypto from 'node:crypto';")
text = text.replace("expect(value.total).toBe(-385);", "expect(value.total).toBe(-485);")
text = text.replace("expect(currentPpk.total).toBe(-940);", "expect(currentPpk.total).toBe(-780);")
text = text.replace("  let results: any[];\n\n  beforeEach(async () => {\n    db = createDatabaseConnection(':memory:');", "  let results: any[];\n  let dbPath = '';\n\n  beforeEach(async () => {\n    dbPath = path.join(os.tmpdir(), `club-game-token-${crypto.randomUUID()}.sqlite`);\n    const raw = new Database(dbPath);\n    raw.exec(fs.readFileSync(path.join(process.cwd(), 'drizzle', '0000_initial.sql'), 'utf8'));\n    raw.exec(`CREATE TABLE IF NOT EXISTS tournament_final_resolutions (\n      id TEXT PRIMARY KEY, tournament_id TEXT NOT NULL, type TEXT NOT NULL, category TEXT,\n      participant_ids_json TEXT NOT NULL, ordered_participant_ids_json TEXT, winner_participant_id TEXT,\n      resolution_method TEXT NOT NULL, comment TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL\n    );`);\n    raw.close();\n    db = createDatabaseConnection(dbPath);")
text = text.replace("  const save = (body: any) =>", "  afterEach(() => {\n    try { db?.sqlite.close(); } catch {}\n    try { if (dbPath && fs.existsSync(dbPath)) fs.unlinkSync(dbPath); } catch {}\n  });\n\n  const save = (body: any) =>")
p.write_text(text, encoding='utf-8')
print('04A focused test harness fixed')
