import { useEffect, useState } from 'react';
import { Check } from 'lucide-react';

type EventItem = { id:string; title:string; starts_at:string; venue?:string|null; event_type:'evening'|'tournament'; participant_count?:number };
type Slot = { id:string; slot_number:number; starts_at:string; price:number; registered_count:number; participants:Array<{id:string;nickname:string}> };
type Plan = { event:EventItem & {assembled:boolean;assembled_slots:number}; slots:Slot[]; selection:{slot_ids:string[];games:number;total:number} };

export default function PlayerEventSlotDetail({event,onBack,onSaved}:{event:EventItem;onBack:()=>void;onSaved:()=>void}){
  const [plan,setPlan]=useState<Plan|null>(null),[draft,setDraft]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{if(event.event_type==='tournament')return;try{const r=await fetch(`/api/player/evenings/${encodeURIComponent(event.id)}/slots`,{credentials:'include'});const b=await r.json();if(!r.ok)throw new Error(b?.error||'Не удалось загрузить игры');setPlan(b);setDraft(b.selection?.slot_ids||[])}catch(e:any){setError(e?.message||'Не удалось загрузить игры')}};
  useEffect(()=>{void load()},[event.id]);
  const save=async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/player/evenings/${encodeURIComponent(event.id)}/slots`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({slot_ids:draft})});const b=await r.json();if(!r.ok)throw new Error(b?.error||'Не удалось сохранить');setPlan(b);setDraft(b.selection?.slot_ids||[]);onSaved()}catch(e:any){setError(e?.message||'Не удалось сохранить')}finally{setBusy(false)}};
  if(event.event_type==='tournament')return <main className="min-h-screen bg-[#090a0d] px-3 pb-28 pt-4 text-white"><div className="mx-auto max-w-[430px]"><button onClick={onBack} className="text-sm text-white/50">← К календарю</button><h1 className="mt-4 text-2xl font-semibold">{event.title}</h1><p className="mt-2 text-sm text-white/45">{new Date(event.starts_at).toLocaleString('ru-RU')}{event.venue?` · ${event.venue}`:''}</p><div className="mt-4 rounded-2xl bg-white/[0.05] p-4 text-sm text-white/50">Участников: {event.participant_count||0}. Турниры используют отдельную регистрацию.</div></div></main>;
  const total=plan?plan.slots.filter(s=>draft.includes(s.id)).reduce((a,s)=>a+s.price,0):0;
  return <main className="min-h-screen bg-[#090a0d] px-3 pb-32 pt-4 text-white"><div className="mx-auto max-w-[430px]"><button onClick={onBack} className="text-sm text-white/50">← К календарю</button><h1 className="mt-4 text-2xl font-semibold">{event.title}</h1><p className="mt-1 text-xs text-white/40">100 ₽ за игру · стол собран, когда минимум 4 игры набрали по 11 человек</p>{error&&<p className="mt-3 text-xs text-rose-300">{error}</p>}
  {plan&&<><div className="mt-4 flex items-center justify-between rounded-2xl bg-white/[0.05] p-3 text-xs"><span>{plan.event.assembled?'Стол собран':'Стол собирается'}</span><b>{plan.event.assembled_slots}/4 игр</b></div><div className="mt-2 flex gap-2"><button onClick={()=>setDraft(plan.slots.map(s=>s.id))} className="flex-1 rounded-xl bg-white/[0.07] py-2 text-xs">Весь вечер</button><button onClick={()=>setDraft([])} className="rounded-xl bg-white/[0.04] px-3 text-xs text-white/45">Очистить</button></div><div className="mt-3 space-y-2">{plan.slots.map(s=>{const on=draft.includes(s.id);return <button key={s.id} onClick={()=>setDraft(x=>on?x.filter(id=>id!==s.id):[...x,s.id])} className={`w-full rounded-2xl border p-3 text-left ${on?'border-white/30 bg-white/[0.10]':'border-white/10 bg-black/20'}`}><div className="flex justify-between"><div><b className="text-sm">Игра {s.slot_number} · {new Date(s.starts_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</b><div className="mt-1 text-xs text-white/40">{s.registered_count} игроков{s.registered_count>=11?' · собрано':''}</div></div><span className={`grid h-7 w-7 place-items-center rounded-full ${on?'bg-white text-black':'bg-white/[0.05]'}`}>{on?<Check className="h-4 w-4"/>:''}</span></div>{s.participants.length>0&&<div className="mt-2 flex flex-wrap gap-1">{s.participants.map(p=><span key={p.id} className="rounded-full bg-white/[0.06] px-2 py-1 text-[10px] text-white/55">{p.nickname}</span>)}</div>}</button>})}</div><div className="fixed inset-x-0 bottom-20 z-50 px-3"><div className="mx-auto max-w-[430px] rounded-2xl bg-[#15171d]/95 p-3 shadow-xl"><div className="mb-2 flex justify-between text-sm"><span>{draft.length} игр</span><b>{total} ₽</b></div><button disabled={busy} onClick={()=>void save()} className="min-h-11 w-full rounded-xl bg-white font-semibold text-black disabled:opacity-50">{busy?'Сохраняю…':'Сохранить мой план'}</button></div></div></>}
  </div></main>;
}
