import { useEffect, useMemo, useState } from 'react';

type Award = { id:string; kind:string; title:string; tournament_name?:string|null; award_date?:string|null; award_year?:number|null; place_result?:string|null; team_name?:string|null; description?:string|null; photo_url?:string|null; pinned_position?:number|null };
type Achievement = { id:string; name:string; description:string; icon:string; rarity_name:string; earned_at:string|null; category_name?:string };
type TimelineItem = { id:string; type:string; date:string|null; icon:string; title:string; description:string|null };
type Showcase = { awards:Award[]; pinned_awards:Award[]; earned_achievements:Achievement[]; timeline:TimelineItem[]; achievements:{earned:number;total:number;percentage:number}; stats:{verified_awards:number;achievements_earned:number;achievements_total:number;completed_games:number;manual_milestones:number} };
const formatDate=(value:string|null|undefined)=>value&&!Number.isNaN(new Date(value).getTime())?new Date(value).toLocaleDateString('ru-RU'):null;

export default function PremiumProfileShowcase({playerId,isSelf,section='all'}:{playerId:string;isSelf:boolean;section?:'all'|'awards'|'history'}){
 const [data,setData]=useState<Showcase|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [nonce,setNonce]=useState(0);
 useEffect(()=>{let cancelled=false;setData(null);setError(null);void fetch(`/api/player/profiles/${encodeURIComponent(playerId)}/showcase`,{credentials:'include'}).then(async r=>{const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||'Не удалось загрузить профиль');return b as Showcase;}).then(b=>{if(!cancelled)setData(b)}).catch((e:any)=>{if(!cancelled)setError(e?.message||'Не удалось загрузить профиль')});return()=>{cancelled=true}},[playerId,nonce]);
 const pinnedIds=useMemo(()=>(data?.pinned_awards||[]).sort((a,b)=>Number(a.pinned_position||0)-Number(b.pinned_position||0)).map(x=>x.id),[data]);
 const togglePin=async(awardId:string)=>{if(!data||busy)return;const current=pinnedIds.includes(awardId)?pinnedIds.filter(id=>id!==awardId):[...pinnedIds,awardId];if(current.length>3)return;setBusy(true);try{const r=await fetch(`/api/player/profiles/${encodeURIComponent(playerId)}/awards/pins`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({award_ids:current})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||'Не удалось закрепить награды');setNonce(v=>v+1)}catch(e:any){setError(e?.message||'Не удалось закрепить награды')}finally{setBusy(false)}};
 if(error&&!data)return <section className="rounded-3xl border border-rose-300/15 p-4 text-sm text-rose-100/80">{error}</section>;
 if(!data)return <section className="rounded-3xl border border-white/10 px-4 py-10 text-center text-sm text-white/45">Загрузка…</section>;
 const showAwards=section==='all'||section==='awards'; const showHistory=section==='all'||section==='history';
 return <div data-testid="premium-profile-showcase" className="space-y-3">
  {showAwards&&<><section className="rounded-3xl border border-white/10 bg-gradient-to-b from-amber-100/[0.07] to-white/[0.035] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Витрина наград</h2><p className="mt-1 text-sm text-white/45">Только проверенные достижения и официальные результаты.</p></div><span className="rounded-full bg-white/[0.07] px-2.5 py-1 text-xs text-white/55">{data.stats.verified_awards}</span></div>{data.awards.length?<div className="mt-4 grid gap-2 sm:grid-cols-2">{data.awards.map(a=>{const pinned=pinnedIds.includes(a.id);return <article key={a.id} className="rounded-2xl border border-white/[0.06] bg-black/20 p-3">{a.photo_url&&<img src={a.photo_url} alt="" className="mb-3 h-32 w-full rounded-xl object-cover"/>}<div className="text-sm font-semibold">🏆 {a.title}</div><div className="mt-1 text-xs text-white/40">{[a.tournament_name,a.place_result,formatDate(a.award_date)||a.award_year].filter(Boolean).join(' · ')}</div>{a.description&&<p className="mt-2 text-xs text-white/45">{a.description}</p>}{isSelf&&<button disabled={busy||(!pinned&&pinnedIds.length>=3)} onClick={()=>void togglePin(a.id)} className="mt-3 min-h-10 w-full rounded-xl border border-white/10 text-xs disabled:opacity-35">{pinned?'Убрать из закреплённых':pinnedIds.length>=3?'Закреплено 3':'Закрепить'}</button>}</article>})}</div>:<div className="mt-4 text-sm text-white/40">Проверенных наград пока нет.</div>}</section><section className="rounded-3xl border border-white/10 bg-white/[0.045] p-4"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Достижения</h2><p className="text-sm text-white/45">Автоматические игровые достижения.</p></div><strong>{data.achievements.earned}/{data.achievements.total}</strong></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{data.earned_achievements.map(x=><article key={x.id} className="rounded-2xl bg-black/20 p-3"><b className="text-sm">{x.icon} {x.name}</b><p className="mt-1 text-xs text-white/45">{x.description}</p></article>)}</div></section></>}
  {showHistory&&<section className="rounded-3xl border border-white/10 bg-white/[0.045] p-4"><h2 className="text-lg font-semibold">История в клубе</h2><p className="mt-1 text-sm text-white/45">Игры, проверенные награды, достижения и подтверждённые этапы.</p>{data.timeline.length?<div className="mt-4 space-y-2">{data.timeline.map(x=><div key={`${x.type}:${x.id}`} className="flex gap-3 rounded-2xl bg-black/20 p-3"><span>{x.icon}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="text-sm">{x.title}</b><time className="text-[11px] text-white/30">{formatDate(x.date)}</time></div>{x.description&&<p className="mt-1 text-xs text-white/45">{x.description}</p>}</div></div>)}</div>:<div className="mt-3 text-sm text-white/40">История клуба появится после подтверждённых событий.</div>}</section>}
 </div>;
}
