import { useEffect, useState } from 'react';
import { CalendarPlus } from 'lucide-react';
import MobileSheet from '../ui/MobileSheet.tsx';

type CustomEvent = { id:string; title:string; starts_at:string; ends_at:string; venue:string; status:string; participant_count:number; participant_limit:number; visibility:string; registration_open:number; announce_telegram_channel:number; announce_club_group:number; announce_vk:number; announce_bot_dm:number };
type Player = { id:string; nickname:string };
const field = 'w-full min-h-11 rounded-[12px] border border-white/10 bg-black/20 px-3 text-[14px] text-white outline-none placeholder:text-white/35';
const label = 'mb-1.5 block text-[12px] font-semibold text-white/60';
const iso = (value:string) => `${value.length === 16 ? `${value}:00` : value}+03:00`;
const display = (value:string) => new Date(value).toLocaleString('ru-RU',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Moscow'});

export default function CustomEventsPanel() {
  const [items,setItems]=useState<CustomEvent[]>([]), [open,setOpen]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState('');
  const [players,setPlayers]=useState<Player[]>([]),[inviteIds,setInviteIds]=useState<string[]>([]),[announcementMessage,setAnnouncementMessage]=useState('');
  const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[startsAt,setStartsAt]=useState(''),[endsAt,setEndsAt]=useState(''),[deadline,setDeadline]=useState(''),[venue,setVenue]=useState('Суп с Котом'),[limit,setLimit]=useState(20),[price,setPrice]=useState(0),[visibility,setVisibility]=useState('everyone'),[allowGuest,setAllowGuest]=useState(false),[cover,setCover]=useState<string|null>(null);
  const [tgChannel,setTgChannel]=useState(false),[clubGroup,setClubGroup]=useState(false),[vk,setVk]=useState(false),[botDm,setBotDm]=useState(false);
  const load=async()=>{const r=await fetch('/api/custom-events/manage',{credentials:'include'});const b=await r.json().catch(()=>[]);if(!r.ok)throw new Error(b.error||'Не удалось загрузить ивенты');setItems(Array.isArray(b)?b:[]);};
  const loadPlayers=async()=>{if(players.length)return;const r=await fetch('/api/players',{credentials:'include'});const b=await r.json().catch(()=>[]);if(r.ok)setPlayers((Array.isArray(b)?b:[]).map((x:any)=>({id:String(x.id),nickname:String(x.nickname||'Игрок')})).sort((a:Player,b:Player)=>a.nickname.localeCompare(b.nickname,'ru')));};
  useEffect(()=>{void load().catch((e)=>setError(e.message));},[]);
  const pickCover=(file?:File)=>{if(!file)return;if(file.size>1_000_000){setError('Обложка должна быть меньше 1 МБ');return;}const reader=new FileReader();reader.onload=()=>setCover(typeof reader.result==='string'?reader.result:null);reader.readAsDataURL(file);};
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/custom-events',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,cover_image_data_url:cover,starts_at:iso(startsAt),ends_at:iso(endsAt),signup_deadline:deadline?iso(deadline):null,venue,participant_limit:limit,price_rub:price,visibility,allow_guest:allowGuest,registration_open:true,announce_telegram_channel:tgChannel,announce_club_group:clubGroup,announce_vk:vk,announce_bot_dm:botDm})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Не удалось создать ивент');if(visibility==='invite'&&inviteIds.length){const invitations=await fetch(`/api/custom-events/${encodeURIComponent(b.id)}/invitations`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({player_ids:inviteIds})});const invitationsBody=await invitations.json().catch(()=>({}));if(!invitations.ok)throw new Error(invitationsBody.error||'Ивент создан, но приглашения не сохранились');}setOpen(false);setTitle('');setDescription('');setCover(null);setInviteIds([]);await load();}catch(x:any){setError(x.message||'Не удалось создать ивент');}finally{setBusy(false);}};
  const setStatus=async(item:CustomEvent,status:string)=>{setError('');const r=await fetch(`/api/custom-events/${encodeURIComponent(item.id)}/status`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const b=await r.json().catch(()=>({}));if(!r.ok){setError(b.error||'Не удалось изменить статус');return;}await load();};
  const toggleRegistration=async(item:CustomEvent)=>{setError('');const r=await fetch(`/api/custom-events/${encodeURIComponent(item.id)}`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({registration_open:!Number(item.registration_open)})});const b=await r.json().catch(()=>({}));if(!r.ok){setError(b.error||'Не удалось изменить запись');return;}await load();};
  const announce=async(item:CustomEvent)=>{setBusy(true);setError('');setAnnouncementMessage('');try{const r=await fetch(`/api/custom-events/${encodeURIComponent(item.id)}/announce`,{method:'POST',credentials:'include'});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'Не удалось отправить анонс');const sent=(b.results||[]).filter((x:any)=>x.status==='sent'||x.status==='queued').length,skipped=(b.results||[]).filter((x:any)=>x.status==='skipped').length,problems=(b.results||[]).filter((x:any)=>!['sent','queued','skipped'].includes(x.status)).length;setAnnouncementMessage(`Анонс: отправлено ${sent}${skipped?`, уже было ${skipped}`:''}${problems?`, требуют настройки ${problems}`:''}.`);}catch(x:any){setError(x.message||'Не удалось отправить анонс');}finally{setBusy(false);}};
  return <>
    <section className="rounded-[20px] border border-fuchsia-300/15 bg-fuchsia-300/[0.05] p-4">
      <h2 className="text-[16px] font-bold text-white">Свои ивенты</h2><p className="mt-1 text-[12px] leading-5 text-white/55">Отдельные события без игр в мафию и без влияния на игровую статистику.</p>
      <button type="button" onClick={()=>{setError('');setOpen(true);}} className="mt-3 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-[12px] bg-white text-[14px] font-semibold text-[#090a0d]"><CalendarPlus className="h-4 w-4"/>Создать ивент</button>
      {error?<p className="mt-2 rounded-xl bg-rose-500/10 px-3 py-2 text-[12px] text-rose-200">{error}</p>:null}{announcementMessage?<p className="mt-2 rounded-xl bg-emerald-500/10 px-3 py-2 text-[12px] text-emerald-100">{announcementMessage}</p>:null}
    </section>
    <section className="overflow-hidden rounded-[18px] border border-white/10 bg-white/[0.03]"><h3 className="px-3.5 pt-3 text-[12px] font-semibold uppercase tracking-[0.12em] text-white/45">Мои ивенты</h3>
      {items.length?items.map(item=><article key={item.id} className="border-t border-white/[0.07] px-3.5 py-3"><div className="flex items-start justify-between gap-3"><div><strong className="text-[14px] text-white">{item.title}</strong><div className="mt-1 text-[12px] text-white/50">{display(item.starts_at)} · {item.venue||'место не указано'}</div><div className="mt-1 text-[12px] text-white/40">{item.participant_count}/{item.participant_limit} мест · {item.status==='draft'?'черновик':item.status==='published'?'опубликован':item.status==='cancelled'?'отменён':'завершён'} · {Number(item.registration_open)?'запись открыта':'запись закрыта'}</div></div>{item.status==='draft'?<button type="button" onClick={()=>void setStatus(item,'published')} className="min-h-10 shrink-0 rounded-xl bg-white px-3 text-[12px] font-semibold text-black">Опубликовать</button>:item.status==='published'?<button type="button" onClick={()=>void setStatus(item,'cancelled')} className="min-h-10 shrink-0 rounded-xl bg-white/[0.07] px-3 text-[12px] font-semibold text-white/60">Отменить</button>:null}</div>{item.status==='published'?<div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>void toggleRegistration(item)} className="min-h-10 rounded-xl bg-white/[0.05] px-3 text-[12px] font-semibold text-white/60">{Number(item.registration_open)?'Закрыть запись':'Открыть запись'}</button><button disabled={busy||![item.announce_telegram_channel,item.announce_club_group,item.announce_vk,item.announce_bot_dm].some(Number)} type="button" onClick={()=>void announce(item)} className="min-h-10 rounded-xl bg-fuchsia-300/15 px-3 text-[12px] font-semibold text-fuchsia-100 disabled:opacity-35">Отправить анонс</button></div>:null}</article>):<p className="px-3.5 py-4 text-[13px] text-white/50">Ивентов пока нет.</p>}
    </section>
    <MobileSheet open={open} onClose={()=>setOpen(false)} title="Новый ивент"><form onSubmit={create} className="space-y-3">
      <label className="block"><span className={label}>Название</span><input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} className={field}/></label>
      <label className="block"><span className={label}>Описание</span><textarea required rows={4} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)} className={`${field} py-3`}/></label>
      <label className="block"><span className={label}>Обложка · JPG, PNG или WebP до 1 МБ</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>pickCover(e.target.files?.[0])} className={`${field} py-2`}/></label>
      {cover?<img src={cover} alt="Предпросмотр обложки" className="aspect-[16/9] w-full rounded-xl object-cover"/>:null}
      <div className="grid grid-cols-2 gap-2"><label><span className={label}>Начало · Москва</span><input required type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className={field}/></label><label><span className={label}>Окончание</span><input required type="datetime-local" value={endsAt} onChange={e=>setEndsAt(e.target.value)} className={field}/></label></div>
      <label className="block"><span className={label}>Запись до (необязательно)</span><input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} className={field}/></label>
      <label className="block"><span className={label}>Место</span><input value={venue} onChange={e=>setVenue(e.target.value)} className={field}/></label>
      <div className="grid grid-cols-2 gap-2"><label><span className={label}>Лимит людей</span><input type="number" min={1} max={1000} value={limit} onChange={e=>setLimit(Number(e.target.value)||1)} className={field}/></label><label><span className={label}>Цена, ₽</span><input type="number" min={0} value={price} onChange={e=>setPrice(Math.max(0,Number(e.target.value)||0))} className={field}/></label></div>
      <label className="block"><span className={label}>Кто видит</span><select value={visibility} onChange={e=>{setVisibility(e.target.value);if(e.target.value==='invite')void loadPlayers();}} className={field}><option value="everyone">Все игроки</option><option value="club">Только игроки клуба</option><option value="invite">Только по приглашению</option></select></label>
      {visibility==='invite'?<fieldset className="max-h-56 overflow-y-auto rounded-xl bg-black/20 p-2"><legend className="px-1 text-[12px] font-semibold text-white/60">Кого пригласить</legend>{players.length?players.map(player=><label key={player.id} className="flex min-h-10 items-center justify-between border-b border-white/[0.05] px-2 text-[13px]"><span>{player.nickname}</span><input type="checkbox" checked={inviteIds.includes(player.id)} onChange={e=>setInviteIds(current=>e.target.checked?[...current,player.id]:current.filter(id=>id!==player.id))} className="h-5 w-5"/></label>):<p className="p-2 text-[12px] text-white/40">Загружаем игроков…</p>}</fieldset>:null}
      <label className="flex min-h-11 items-center justify-between rounded-xl bg-black/20 px-3 text-[13px]"><span>Разрешить гостя +1</span><input type="checkbox" checked={allowGuest} onChange={e=>setAllowGuest(e.target.checked)} className="h-5 w-5"/></label>
      <fieldset className="rounded-xl bg-black/20 p-3"><legend className="px-1 text-[12px] font-semibold text-white/60">Где анонсировать после публикации</legend>{[[tgChannel,setTgChannel,'Telegram-канал'],[clubGroup,setClubGroup,'Клубная группа'],[vk,setVk,'ВКонтакте'],[botDm,setBotDm,'Личные сообщения бота']] .map(([checked,setChecked,text])=><label key={String(text)} className="flex min-h-10 items-center justify-between text-[13px]"><span>{String(text)}</span><input type="checkbox" checked={Boolean(checked)} onChange={e=>(setChecked as (value:boolean)=>void)(e.target.checked)} className="h-5 w-5"/></label>)}</fieldset>
      <p className="text-[12px] leading-5 text-white/45">Сначала сохранится черновик. Он появится у игроков только после кнопки «Опубликовать».</p>
      <button disabled={busy||!title||!startsAt||!endsAt} className="min-h-12 w-full rounded-xl bg-white text-[14px] font-bold text-black disabled:opacity-40">{busy?'Создаём…':'Создать черновик'}</button>
    </form></MobileSheet>
  </>;
}
