import React, { useEffect, useMemo, useState } from 'react';
import { Award, Coins, Database, History, RefreshCw, ShoppingBag, Users } from 'lucide-react';

type Achievement = {
  id: string; name: string; description: string; icon: string; category: string; metric: string;
  threshold: number; role?: string | null; rarity: string; order: number; active: boolean;
};
type ShopItem = { id: string; name: string; description: string; price: number; icon: string; item_type: string; active: number; sort_order: number };
type Player = { id: string; nickname: string; elo: number; tokens: number; game_level: string };
type Change = { id: string; entity_type: string; entity_id: string | null; action: string; note: string | null; created_at: string };
type Summary = { achievements: Achievement[]; shop_items: ShopItem[]; players: Player[]; changes: Change[] };
type Tab = 'achievements' | 'shop' | 'players' | 'database' | 'log';
type TableMeta = { table: string; label: string; columns: Array<{ name: string; type: string; pk: number; editable: boolean }> };
type TableData = TableMeta & { rows: Array<Record<string, any> & { __pk: string }>; total: number; limit: number; offset: number };

const apiFetch = async <T,>(url: string, options?: RequestInit): Promise<T> => {
  const response = await fetch(url, { credentials: 'include', ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body?.error || 'Ошибка запроса');
  return body as T;
};

const fieldClass = 'mobile-field min-h-[44px]';

function AchievementEditor({ item, onSaved }: { item: Achievement; onSaved: () => Promise<void> }) {
  const [draft, setDraft] = useState({ ...item });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const update = (key: keyof Achievement, value: any) => setDraft((current) => ({ ...current, [key]: value }));
  const save = async () => {
    setSaving(true); setError(null);
    try {
      await apiFetch(`/api/admin-data/achievements/${encodeURIComponent(item.id)}`, { method: 'PATCH', body: JSON.stringify(draft) });
      await onSaved();
    } catch (err: any) { setError(err?.message || 'Не удалось сохранить'); }
    finally { setSaving(false); }
  };
  return <details className="rounded-[16px] border border-border-soft bg-surface-1 p-3">
    <summary className="cursor-pointer list-none"><div className="flex items-center gap-3"><span className="text-2xl">{item.icon}</span><div className="min-w-0 flex-1"><div className="truncate text-[14px] font-bold text-text-primary">{item.name}</div><div className="mt-0.5 text-[11px] text-text-secondary">{item.id} · {item.active ? 'активна' : 'выключена'} · порог {item.threshold}</div></div></div></summary>
    <div className="mt-4 grid gap-3 sm:grid-cols-2">
      <label><span className="mb-1 block text-[11px] text-text-muted">Название</span><input className={fieldClass} value={draft.name} onChange={(e) => update('name', e.target.value)} /></label>
      <label><span className="mb-1 block text-[11px] text-text-muted">Иконка</span><input className={fieldClass} value={draft.icon} onChange={(e) => update('icon', e.target.value)} /></label>
      <label className="sm:col-span-2"><span className="mb-1 block text-[11px] text-text-muted">За что даётся</span><textarea className="mobile-field min-h-[82px]" value={draft.description} onChange={(e) => update('description', e.target.value)} /></label>
      <label><span className="mb-1 block text-[11px] text-text-muted">Условие</span><select className={fieldClass} value={draft.metric} onChange={(e) => update('metric', e.target.value)}><option value="games">Количество игр</option><option value="wins">Победы</option><option value="rating">Elo</option><option value="judged">Отсуженные игры</option><option value="role">Победы на роли</option><option value="pu">ПУ</option><option value="perfect_game">Идеальные игры</option></select></label>
      <label><span className="mb-1 block text-[11px] text-text-muted">Порог</span><input className={fieldClass} type="number" value={draft.threshold} onChange={(e) => update('threshold', Number(e.target.value))} /></label>
      {draft.metric === 'role' ? <label><span className="mb-1 block text-[11px] text-text-muted">Роль</span><select className={fieldClass} value={draft.role || ''} onChange={(e) => update('role', e.target.value)}><option value="sheriff">Шериф</option><option value="mafia">Мафия</option><option value="don">Дон</option></select></label> : null}
      <label><span className="mb-1 block text-[11px] text-text-muted">Редкость</span><select className={fieldClass} value={draft.rarity} onChange={(e) => update('rarity', e.target.value)}><option value="common">Обычная</option><option value="rare">Редкая</option><option value="epic">Эпическая</option><option value="legendary">Легендарная</option></select></label>
      <label><span className="mb-1 block text-[11px] text-text-muted">Категория</span><select className={fieldClass} value={draft.category} onChange={(e) => update('category', e.target.value)}><option value="games">Игровые</option><option value="wins">Победные</option><option value="rating">Рейтинговые</option><option value="roles">Ролевые</option><option value="judge">Судейские</option><option value="special">Особые</option></select></label>
      <label><span className="mb-1 block text-[11px] text-text-muted">Порядок</span><input className={fieldClass} type="number" value={draft.order} onChange={(e) => update('order', Number(e.target.value))} /></label>
      <label className="flex items-center gap-2 pt-5 text-[12px]"><input type="checkbox" checked={draft.active} onChange={(e) => update('active', e.target.checked)} /> Показывать и автоматически выдавать</label>
    </div>
    {error ? <p className="mt-3 text-[12px] font-semibold text-danger">{error}</p> : null}
    <button type="button" disabled={saving} onClick={() => void save()} className="mt-4 min-h-11 w-full rounded-[12px] bg-accent text-[13px] font-bold text-white disabled:opacity-50">{saving ? 'Сохраняем…' : 'Сохранить ачивку'}</button>
  </details>;
}

function ShopEditor({ item, onSaved }: { item: ShopItem; onSaved: () => Promise<void> }) {
  const [draft, setDraft] = useState({ ...item }); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const save = async () => { setSaving(true); setError(null); try { await apiFetch(`/api/admin-data/shop-items/${encodeURIComponent(item.id)}`, { method: 'PATCH', body: JSON.stringify({ ...draft, active: Boolean(draft.active) }) }); await onSaved(); } catch (err: any) { setError(err?.message || 'Ошибка'); } finally { setSaving(false); } };
  return <details className="rounded-[16px] border border-border-soft bg-surface-1 p-3"><summary className="cursor-pointer list-none"><div className="flex items-center gap-3"><span className="text-2xl">{item.icon}</span><div className="min-w-0 flex-1"><div className="truncate text-[14px] font-bold">{item.name}</div><div className="text-[11px] text-text-secondary">{item.price.toLocaleString('ru-RU')} 🪙 · {item.active ? 'продаётся' : 'скрыт'}</div></div></div></summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className={fieldClass} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} placeholder="Название" /><input className={fieldClass} value={draft.icon} onChange={(e) => setDraft({ ...draft, icon: e.target.value })} placeholder="Иконка" /><textarea className="mobile-field min-h-[82px] sm:col-span-2" value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} /><input className={fieldClass} type="number" value={draft.price} onChange={(e) => setDraft({ ...draft, price: Number(e.target.value) })} placeholder="Цена" /><input className={fieldClass} value={draft.item_type} onChange={(e) => setDraft({ ...draft, item_type: e.target.value })} placeholder="Тип" /><input className={fieldClass} type="number" value={draft.sort_order} onChange={(e) => setDraft({ ...draft, sort_order: Number(e.target.value) })} placeholder="Порядок" /><label className="flex items-center gap-2 text-[12px]"><input type="checkbox" checked={Boolean(draft.active)} onChange={(e) => setDraft({ ...draft, active: e.target.checked ? 1 : 0 })} /> Товар активен</label></div>{error ? <p className="mt-3 text-[12px] text-danger">{error}</p> : null}<button onClick={() => void save()} disabled={saving} className="mt-4 min-h-11 w-full rounded-[12px] bg-accent text-[13px] font-bold text-white">{saving ? 'Сохраняем…' : 'Сохранить товар'}</button></details>;
}

function ExpertRowEditor({ row, columns, table, onSaved }: { row: Record<string, any> & { __pk: string }; columns: TableMeta['columns']; table: string; onSaved: () => Promise<void> }) {
  const editable = columns.filter((column) => column.editable);
  const [draft, setDraft] = useState<Record<string, string>>(() => Object.fromEntries(editable.map((column) => [column.name, row[column.name] == null ? '' : String(row[column.name])])));
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const changed = editable.filter((column) => (row[column.name] == null ? '' : String(row[column.name])) !== draft[column.name]);
  const save = async () => {
    if (!changed.length) return;
    const preview = changed.slice(0, 6).map((column) => `${column.name}: ${String(row[column.name] ?? 'NULL')} → ${draft[column.name] || 'NULL'}`).join('\n');
    if (!window.confirm(`Экспертное изменение:\n\n${preview}${changed.length > 6 ? `\n…и ещё ${changed.length - 6}` : ''}\n\nПродолжить?`)) return;
    setSaving(true); setError(null);
    try { await apiFetch(`/api/admin-data/database/${encodeURIComponent(table)}/${encodeURIComponent(row.__pk)}`, { method: 'PATCH', body: JSON.stringify({ changes: Object.fromEntries(changed.map((column) => [column.name, draft[column.name]])), note: 'Ручная правка из экспертного режима' }) }); await onSaved(); }
    catch (err: any) { setError(err?.message || 'Ошибка'); } finally { setSaving(false); }
  };
  return <details className="rounded-[14px] border border-border-soft bg-surface-1 p-3"><summary className="cursor-pointer text-[12px] font-bold text-text-primary">{row.__pk}</summary><div className="mt-3 space-y-2">{editable.map((column) => <label key={column.name} className="block"><span className="mb-1 block text-[10px] text-text-muted">{column.name} · {column.type || 'TEXT'}</span><input className={fieldClass} value={draft[column.name] ?? ''} onChange={(e) => setDraft({ ...draft, [column.name]: e.target.value })} /></label>)}</div>{error ? <p className="mt-2 text-[12px] text-danger">{error}</p> : null}<button disabled={!changed.length || saving} onClick={() => void save()} className="mt-3 min-h-10 w-full rounded-[10px] bg-danger/90 text-[12px] font-bold text-white disabled:opacity-35">{saving ? 'Сохраняем…' : `Применить ${changed.length ? `(${changed.length})` : ''}`}</button></details>;
}

export const DataSettingsCRM: React.FC = () => {
  const [tab, setTab] = useState<Tab>('achievements'); const [summary, setSummary] = useState<Summary | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [playerId, setPlayerId] = useState(''); const [tokenDelta, setTokenDelta] = useState(''); const [reason, setReason] = useState(''); const [achievementId, setAchievementId] = useState(''); const [actionMessage, setActionMessage] = useState<string | null>(null);
  const [tables, setTables] = useState<TableMeta[]>([]); const [tableName, setTableName] = useState(''); const [tableData, setTableData] = useState<TableData | null>(null); const [tableLoading, setTableLoading] = useState(false);
  const loadSummary = async () => { setError(null); try { const body = await apiFetch<Summary>('/api/admin-data/summary'); setSummary(body); if (!playerId && body.players[0]) setPlayerId(body.players[0].id); if (!achievementId && body.achievements[0]) setAchievementId(body.achievements[0].id); } catch (err: any) { setError(err?.message || 'Не удалось загрузить данные'); } finally { setLoading(false); } };
  useEffect(() => { void loadSummary(); }, []);
  useEffect(() => { if (tab !== 'database' || tables.length) return; void apiFetch<{ tables: TableMeta[] }>('/api/admin-data/database/tables').then((body) => { setTables(body.tables); if (body.tables[0]) setTableName(body.tables[0].table); }).catch((err) => setError(err?.message || 'Не удалось загрузить таблицы')); }, [tab, tables.length]);
  const loadTable = async (name = tableName) => { if (!name) return; setTableLoading(true); try { setTableData(await apiFetch<TableData>(`/api/admin-data/database/${encodeURIComponent(name)}`)); } catch (err: any) { setError(err?.message || 'Не удалось загрузить таблицу'); } finally { setTableLoading(false); } };
  useEffect(() => { if (tab === 'database' && tableName) void loadTable(tableName); }, [tab, tableName]);
  const selectedPlayer = useMemo(() => summary?.players.find((player) => player.id === playerId) || null, [summary, playerId]);
  const adjustTokens = async () => { if (!playerId || !tokenDelta || !reason.trim()) return; setActionMessage(null); try { await apiFetch(`/api/admin-data/players/${encodeURIComponent(playerId)}/tokens`, { method: 'POST', body: JSON.stringify({ delta: Number(tokenDelta), reason }) }); setTokenDelta(''); setReason(''); setActionMessage('Баланс жетонов изменён'); await loadSummary(); } catch (err: any) { setActionMessage(err?.message || 'Ошибка'); } };
  const changeAchievement = async (state: 'grant' | 'revoke' | 'auto') => { if (!playerId || !achievementId) return; setActionMessage(null); try { await apiFetch(`/api/admin-data/players/${encodeURIComponent(playerId)}/achievements/${encodeURIComponent(achievementId)}`, { method: 'POST', body: JSON.stringify({ state, note: 'Ручная настройка из админки' }) }); setActionMessage(state === 'grant' ? 'Ачивка выдана' : state === 'revoke' ? 'Ачивка забрана' : 'Вернули автоматический режим'); await loadSummary(); } catch (err: any) { setActionMessage(err?.message || 'Ошибка'); } };
  if (loading) return <div className="flex min-h-[40vh] items-center justify-center"><RefreshCw className="h-6 w-6 animate-spin text-accent" /></div>;
  return <div className="mx-auto w-full max-w-2xl space-y-4"><div><h2 className="text-[24px] font-black tracking-tight">Данные и настройки</h2><p className="mt-1 text-[13px] text-text-secondary">Ручное управление каталогами, начислениями и значениями базы. Все изменения журналируются.</p></div>{error ? <div className="rounded-[14px] border border-danger/30 bg-danger-soft p-3 text-[12px] text-danger">{error}</div> : null}<div className="grid grid-cols-5 gap-1 rounded-[14px] border border-border-soft bg-surface-1 p-1">{([{ id: 'achievements', icon: Award, label: 'Ачивки' }, { id: 'shop', icon: ShoppingBag, label: 'Магазин' }, { id: 'players', icon: Users, label: 'Игроки' }, { id: 'database', icon: Database, label: 'База' }, { id: 'log', icon: History, label: 'Журнал' }] as const).map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`flex min-h-[52px] min-w-0 flex-col items-center justify-center rounded-[10px] px-1 text-[9px] font-bold ${tab === item.id ? 'bg-accent text-white' : 'text-text-muted'}`}><item.icon className="mb-1 h-4 w-4" />{item.label}</button>)}</div>
    {tab === 'achievements' ? <div className="space-y-2">{summary?.achievements.map((item) => <AchievementEditor key={item.id} item={item} onSaved={loadSummary} />)}</div> : null}
    {tab === 'shop' ? <div className="space-y-2">{summary?.shop_items.map((item) => <ShopEditor key={item.id} item={item} onSaved={loadSummary} />)}</div> : null}
    {tab === 'players' ? <div className="space-y-4"><section className="rounded-[18px] border border-border-soft bg-surface-1 p-4"><label className="text-[11px] text-text-muted">Игрок</label><select className={`${fieldClass} mt-1`} value={playerId} onChange={(e) => setPlayerId(e.target.value)}>{summary?.players.map((player) => <option key={player.id} value={player.id}>{player.nickname} · {player.tokens} 🪙 · Elo {player.elo}</option>)}</select>{selectedPlayer ? <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-[12px] bg-surface-2 p-3"><div className="text-[10px] text-text-muted">Жетоны</div><div className="mt-1 text-[18px] font-black">{selectedPlayer.tokens.toLocaleString('ru-RU')}</div></div><div className="rounded-[12px] bg-surface-2 p-3"><div className="text-[10px] text-text-muted">Elo</div><div className="mt-1 text-[18px] font-black">{selectedPlayer.elo}</div></div></div> : null}</section><section className="rounded-[18px] border border-border-soft bg-surface-1 p-4"><div className="mb-3 flex items-center gap-2 text-[14px] font-bold"><Coins className="h-4 w-4 text-accent" /> Ручные жетоны</div><div className="grid gap-2 sm:grid-cols-2"><input className={fieldClass} type="number" value={tokenDelta} onChange={(e) => setTokenDelta(e.target.value)} placeholder="+5000 или -500" /><input className={fieldClass} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Причина изменения" /></div><button onClick={() => void adjustTokens()} className="mt-3 min-h-11 w-full rounded-[12px] bg-accent text-[13px] font-bold text-white">Начислить / списать</button></section><section className="rounded-[18px] border border-border-soft bg-surface-1 p-4"><div className="mb-3 text-[14px] font-bold">Ручные достижения</div><select className={fieldClass} value={achievementId} onChange={(e) => setAchievementId(e.target.value)}>{summary?.achievements.map((achievement) => <option key={achievement.id} value={achievement.id}>{achievement.icon} {achievement.name}</option>)}</select><div className="mt-3 grid grid-cols-3 gap-2"><button onClick={() => void changeAchievement('grant')} className="min-h-11 rounded-[11px] bg-accent text-[11px] font-bold text-white">Выдать</button><button onClick={() => void changeAchievement('revoke')} className="min-h-11 rounded-[11px] bg-danger-soft text-[11px] font-bold text-danger">Забрать</button><button onClick={() => void changeAchievement('auto')} className="min-h-11 rounded-[11px] bg-surface-2 text-[11px] font-bold">Авто</button></div></section>{actionMessage ? <div className="rounded-[12px] bg-surface-2 p-3 text-[12px]">{actionMessage}</div> : null}<p className="text-[11px] leading-5 text-text-muted">Elo, уровень игрока и прочие поля можно исправить во вкладке «База». Баланс жетонов намеренно меняется только через журналируемую операцию выше.</p></div> : null}
    {tab === 'database' ? <div className="space-y-3"><div className="rounded-[16px] border border-danger/25 bg-danger-soft p-3 text-[12px] leading-5 text-danger"><strong>Экспертный режим.</strong> Здесь можно исправлять рабочие записи напрямую. ID и бинарные данные заблокированы, а жетоны меняются только через ledger. Каждая правка попадёт в журнал.</div><select className={fieldClass} value={tableName} onChange={(e) => setTableName(e.target.value)}>{tables.map((table) => <option key={table.table} value={table.table}>{table.label} · {table.table}</option>)}</select>{tableLoading ? <div className="py-8 text-center"><RefreshCw className="mx-auto h-5 w-5 animate-spin" /></div> : tableData ? <div className="space-y-2"><div className="text-[11px] text-text-muted">Записей: {tableData.total}. Показаны первые {tableData.rows.length}.</div>{tableData.rows.map((row) => <ExpertRowEditor key={row.__pk} row={row} columns={tableData.columns} table={tableData.table} onSaved={() => loadTable(tableData.table)} />)}</div> : null}</div> : null}
    {tab === 'log' ? <div className="space-y-2">{summary?.changes.length ? summary.changes.map((change) => <div key={change.id} className="rounded-[14px] border border-border-soft bg-surface-1 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[12px] font-bold">{change.entity_type} · {change.action}</div><div className="mt-1 truncate text-[10px] text-text-muted">{change.entity_id || '—'}</div></div><div className="shrink-0 text-[10px] text-text-muted">{new Date(change.created_at).toLocaleString('ru-RU')}</div></div>{change.note ? <div className="mt-2 text-[11px] text-text-secondary">{change.note}</div> : null}</div>) : <div className="rounded-[14px] bg-surface-1 p-4 text-[12px] text-text-muted">Изменений пока нет.</div>}</div> : null}
  </div>;
};

export default DataSettingsCRM;
