import React,{useEffect,useState} from 'react';

type Person={id:string;nickname:string};
type Slot={id:string;slot_number:number;starts_at:string;ends_at:string;price:number;registered_count:number;participants:Person[]};
type Plan={event:{slot_count:number;price_per_game:number;assembled:boolean;assembled_slots:number;required_slots:number;required_players_per_slot:number};slots:Slot[]};
const tm=(v:string)=>new Date(v).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});

export default function EveningSlotPlannerCard({eveningId,onRefresh}:{eveningId:string;onRefresh?:()=>void}){
 const [plan,setPlan]=useState<Plan|null>(null),[count,setCount]=useState(6),[price,setPrice]=useState(100),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{setError('');try{const r=await fetch(`/api/evenings/${encodeURIComponent(eveningId)}/slots`,{credentials:'include'}),b=await r.json();if(!r.ok)throw new Error(b?.error||'Не удалось загрузить игровые слоты');setPlan(b);setCount(Number(b.event?.slot_count||6));setPrice(Number(b.event?.price_per_game??100));}catch(e:any){setError(e?.message||'Не удалось загрузить игровые слоты')}};
 useEffect(()=>{void load()},[eveningId]);
 const save=async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/evenings/${encodeURIComponent(eveningId)}/slots`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({planned_slots:count,price_per_game:price})}),b=await r.json();if(!r.ok)throw new Error(b?.error||'Не удалось сохранить план');setPlan(b);onRefresh?.();}catch(e:any){setError(e?.message||'Не удалось сохранить план')}finally{setBusy(false)}};
 return <section className="rounded-3xl border border-border-soft bg-surface-1 p-4 sm:p-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.15em] text-text-muted">План вечера</div><h2 className="mt-1 text-lg font-black text-text-primary">Игровые слоты</h2><p className="mt-1 text-xs text-text-secondary">1 игра = 1 час. Стол собран, когда минимум 4 игры набрали по 11 игроков.</p></div>{plan&&<span className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${plan.event.assembled?'bg-success-soft text-success':'bg-surface-2 text-text-secondary'}`}>{plan.event.assembled?'Стол собран':`${plan.event.assembled_slots}/${plan.event.required_slots} игр собрано`}</span>}</div>
  <div className="mt-4 grid grid-cols-[1fr_1fr_auto] gap-2"><label className="text-[10px] font-bold uppercase text-text-muted">Игр<select value={count} onChange={e=>setCount(Number(e.target.value))} className="mt-1 min-h-11 w-full rounded-xl border border-border-soft bg-surface-2 px-3 text-sm text-text-primary">{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label><label className="text-[10px] font-bold uppercase text-text-muted">Цена / игра<input type="number" min="0" value={price} onChange={e=>setPrice(Math.max(0,Number(e.target.value||0)))} className="mt-1 min-h-11 w-full rounded-xl border border-border-soft bg-surface-2 px-3 text-sm text-text-primary"/></label><button disabled={busy} onClick={()=>void save()} className="mt-5 min-h-11 rounded-xl bg-accent px-4 text-xs font-bold text-white disabled:opacity-50">{busy?'…':'Сохранить'}</button></div>
  {error&&<div className="mt-3 rounded-xl bg-danger-soft px-3 py-2 text-xs text-text-secondary">{error}</div>}
  {plan&&<div className="mt-4 grid gap-2 lg:grid-cols-2">{plan.slots.map(s=>{const ready=s.registered_count>=plan.event.required_players_per_slot;return <div key={s.id} className={`rounded-2xl border p-3 ${ready?'border-success/30 bg-success-soft/30':'border-border-soft bg-surface-2'}`}><div className="flex justify-between gap-2"><div><b className="text-sm text-text-primary">Игра {s.slot_number} · {tm(s.starts_at)}–{tm(s.ends_at)}</b><div className={`mt-1 text-[11px] ${ready?'text-success':'text-text-secondary'}`}>{s.registered_count}/{plan.event.required_players_per_slot} игроков{ready?' · собрано':''}</div></div><span className="text-[10px] text-text-muted">{s.price} ₽</span></div>{s.participants.length?<div className="mt-2 flex flex-wrap gap-1">{s.participants.map(p=><span key={p.id} className="rounded-full bg-surface-1 px-2 py-1 text-[10px] text-text-secondary">{p.nickname}</span>)}</div>:<div className="mt-2 text-[10px] text-text-muted">Пока пусто</div>}</div>})}</div>}
 </section>;
}
